quit -sim
if {[file exists work]} {
  vdel -all -lib work
}

vlib work
vlog  +define+SIMULATION -work work  "mt48lc2m32b2.v"
vlog  +define+SIMULATION -work work  "MX25V1635F.v"
vlog  +define+SIMULATION -work work  "../../../cores/wb_switch/wb_switch.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_wb_master.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_jmp_cond.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_regfile.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_mux8_1.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_mux8_16.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_othop.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_rxr16.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_rxr8.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_shrot.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_fulladd16.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_arlog.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_bitlog.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_div_uu.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_div_su.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/altera/zet_signmul17.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_muldiv.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_conv.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_addsub.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_alu.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_exec.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_micro_rom.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_micro_data.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_memory_regs.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_opcode_deco.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_decode.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_nstate.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_next_or_not.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_fetch.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet_core.v"
vlog  +define+SIMULATION -work work  "../../../cores/zet/rtl/zet.v"
vlog  +define+SIMULATION -work work  "../../../cores/sdspi/rtl/sdspi.v"
vlog  +define+SIMULATION -work work  "../../../cores/wb_abrg/wb_abrgr.v"
vlog  +define+SIMULATION -work work  "../../../cores/pic/rtl/simple_pic.v"
vlog  +define+SIMULATION -work work  "../../../cores/timer/rtl/timer_counter.v"
vlog  +define+SIMULATION -work work  "../../../cores/timer/rtl/timer.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_keyb_xtcodes.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_keyb.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_mouse_datain.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_mouse_cmdout.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_mouse.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2_mouse_nofifo.v"
vlog  +define+SIMULATION -work work  "../../../cores/ps2/rtl/ps2.v"
# vlog  +define+SIMULATION -work work  "../../../cores/serial/rtl/serial_atx.v"
# vlog  +define+SIMULATION -work work  "../../../cores/serial/rtl/serial_arx.v"
# vlog  +define+SIMULATION -work work  "../../../cores/serial/rtl/serial.v"
vlog  +define+SIMULATION -work work  "../../../cores/fmlbrg/rtl/fmlbrg_datamem.v"
vlog  +define+SIMULATION -work work  "../../../cores/fmlbrg/rtl/fmlbrg_tagmem.v"
vlog  +define+SIMULATION -work work  "../../../cores/fmlbrg/rtl/fmlbrg.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_c4_iface.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_write_iface.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_read_iface.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_cpu_mem_iface.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_dac_regs_fml.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_palette_regs_fml.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_pal_dac_fml.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_fifo.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_lcd_fml.v"
# vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/vga_dac_regs_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/vga_palette_regs_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/vga_pal_dac_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/atxfifo.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_linear_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_planar_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_char_rom.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_text_mode_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_sequencer_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/vga_crtc_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/vga_lcd_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/vga_config_iface.v"
vlog  +define+SIMULATION -work work  "../../../cores/vga/rtl/fml/dc/vga_fml.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_cfg.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_sdrio.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_banktimer.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_datactl.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_busif.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_mgmt.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc_ctlif.v"
vlog  +define+SIMULATION -work work  "../../../cores/hpdmc_sdr16/rtl/hpdmc.v"
vlog  +define+SIMULATION -work work  "../../../cores/fmlarb/rtl/fmlarb.v"
vlog  +define+SIMULATION -work work  "../../../cores/csrbrg/rtl/csrbrg.v"
vlog  +define+SIMULATION -work work  "../../../cores/flash/spinor.v"
vlog  +define+SIMULATION -work work  "../../../cores/flash/wbspinor.v"
vlog  +define+SIMULATION -work work  "../../../cores/flash/bootrom.v"
vlog  +define+SIMULATION -work work  "../../../cores/timer/rtl/clk_gen.v"
vlog  +define+SIMULATION -work work  "../../../cores/gpio/rtl/leds2.v"
# vlog  +define+SIMULATION -work work  "../rtl/pll1.v"
vlog  +define+SIMULATION -work work  "../rtl/pll2.v"
vlog  +define+SIMULATION -work work  "../rtl/kotku.v"
vlog  +define+SIMULATION -work work  "test_kotku.v"